--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Ree-jp/StackStrage
build-by-default: true
branches:
  - master
  - one_chest
projects:
  StackStrage:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^3.4
...
