--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Ree-jp/StackStrage
build-by-default: true
branches:
  - master
  - fix/pm4-inv
projects:
  StackStrage:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: 4.1.*
      - src: SOF3/await-generator/await-generator
        version: ^3.5
#      - src: muqsit/InvMenu/InvMenu
#        version: ^4.5
#        branch: "4.0"
...
