--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Ree-jp/StackStrage
build-by-default: true
branches:
  - master
  - test/await
projects:
  StackStrage:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^3.4
      - src: SOF3/await-generator/await-generator
      - src: muqsit/InvMenu/InvMenu
        version: ^4.3
        branch: "4.0"
...
