name: StackStorage
main: ree_jp\stackstorage\StackStoragePlugin
api: 5.0.0
version: 2.0.0
author: Ree-jp
website: https://github.com/Ree-jp-minecraft/StackStrage
description: infinity storage
extensions:
  Core: '>=8.1'
permissions:
  stackstorage.command.my:
    description: Open your storage
    default: true
  stackstorage.command.user:
    description: Open another user's storage
    default: op
  stackstorage.command.check:
    description: check storage
    default: op
