name: StackStorage
main: ree_jp\stackStorage\StackStoragePlugin
api : 3.0.0
version: 1.1.4
author: Ree-jp
extensions:
  Core: '>=8.0'
permissions:
  stackstorage.command:
    default: true
    children:
      stackstorage.command.my:
        default: true
      stackstorage.command.user:
        default: op
